[package]
name = "mercury_oxide"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "mercury_oxide"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.21.0"
lazy_static = "1.0"
liquid = "0.18"